version: "3.8"
services:
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    volumes:
      - ./opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
  localstack:
    image: localstack/localstack:2.1.0
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3,sns,sqs
