on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install node
      uses: actions/setup-node@master
      with:
        node-version: 14.18

    - name: npm install
      run: npm install

    - name: npm run test
      run: npm run test

