on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
          - 9300:9300
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3,sns,sqs
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: package.json
      - name: Upgrade npm
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm install
      - name: Eslint
        run: npm run lint
      - name: Audit
        run: npm audit --omit dev
      - name: Unit tests
        run: npm run test:coverage
      - name: System tests
        run: npm run test:system
