on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - '**'
  merge_group:
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3,sns,sqs
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: package.json
      - uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: 2.11
      - name: Upgrade npm
        run: npm install -g npm@8.19.4
      - name: Install dependencies
        run: npm install
      - name: Eslint
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck
      - name: Audit
        run: npm run audit-prod
      - name: Unit tests
        run: npm run test:coverage
      - name: Wait for OpenSearch
        run: ./bin/wait-for-opensearch/run.sh
      - name: System tests
        run: npm run test:system
      - name: Run build
        run: npm run build
