on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@master
        with:
          node-version: '14.18'

      - run: npm install -g npm@latest

      - run: npm install

      - run: npm run lint

      - run: npm audit --omit dev

      - run: npm run test:coverage
